# Generated by Django 4.2.2 on 2023-06-14 09:09

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_user', models.CharField(max_length=100)),
                ('add_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_loaction', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('company_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='todo_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=core.models.one_week_hence)),
                ('status', models.CharField(max_length=100)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todo_list')),
            ],
        ),
    ]
