# Generated by Django 4.2.2 on 2023-06-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_company_todo_list_upcoming_add_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_user',
        ),
    ]
