# Generated by Django 4.2.2 on 2023-06-14 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_admin_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='drive_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
